services:
  nginx:
    image: nginx
    volumes: 
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    restart: always
    ports: 
      - "7779:80"
    container_name: p_nginx

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: audiojs
      MYSQL_ROOT_PASSWORD: mypassnigga
    ports:
      - "7771:3306"  
    container_name: project_db


  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./sessi:/tmp    
    container_name: p_app

