services:
  nginx:
    image: nginx
    volumes: 
      - ./:/var/www/audiojs
      # - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    restart: always
    ports: 
      - "7779:80"
    container_name: p_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/audiojs
      - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./sessi:/tmp    
    container_name: p_app

